version: 2

workflows:
  version: 2
  build:
    jobs:
      - docker_image:
          filters:
            tags:
              only: /.*/

jobs:
  docker_image:
    docker:
      - image: remind101/docker-build@sha256:eb1001b5d8efd946039c4b0ac181640970230f4e3f69e49c5359ba70fde1a926
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker-build
