version: 2

workflows:
  version: 2
  build:
    jobs:
      - docker_image

jobs:
  docker_image:
    docker:
      - image: remind101/docker-build@sha256:293984f8ff69d509b3ce9f00e27e89ecc3ae7b4eb6e629cf4b77931749c0cc2e
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker-build
