version: 2

workflows:
  version: 2
  build:
    jobs:
      - lint
      - docker_image:
          context:
            - docker-hub
          requires:
            - lint

jobs:
  lint:
    docker:
      # We need this to be less than 3.14 because 3.14 introduces
      # https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2,
      # which breaks with older versions of docker. The underlying CircleCI
      # runtime is still on Docker 19.
      - image: library/alpine:3.13
    steps:
      - checkout
      - run: apk --update add make shellcheck
      - run: |
          make lint

  docker_image:
    docker:
      # https://github.com/remind101/docker-build/commit/060f016731f0b554c6648669703978c895eb8ca5
      - image: remind101/docker-build@sha256:3c48340d29d6d5aa46773bae93c7eb3b2d994ecd25e02707119dccd7b914967e
    environment:
      DOCKER_BUILDKIT: 1
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.12
      - run: printenv DOCKER_PASS | docker login -u "$DOCKER_USER" --password-stdin
      - run: docker-build
